name: pull-request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4
      - name: Run Makefile
        run: make build

  pr-ready:
    runs-on: ubuntu-latest
    if: always()
    needs: [ build-and-validate ]
    steps:
      - name: Emit the final result of workflow for required status check
        run: |
          if [[ '${{ needs.build-and-validate.result }}' != 'success' ]]; then
            echo '::error::build-and-validate job had issues'
            exit 1
          fi

